### ISSUE TITLE
Unhandled exception on API errors

### ISSUE THREAD

**Issue by slonokot** [adamyodinsky/TerminalGPT#22]
**Describe the bug**
If openapi API is down - returns non 20x response the exception is thrown:

```shell
User:  some prompt request

Traceback (most recent call last):
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 672, in _interpret_response_line
    data = json.loads(rbody)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/terminalgpt", line 8, in <module>
    sys.exit(cli())
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/terminalgpt/main.py", line 82, in new
    chat_utils.chat_loop(
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/terminalgpt/chat_utils.py", line 49, in chat_loop
    answer = get_user_answer(messages)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/terminalgpt/chat_utils.py", line 101, in get_user_answer
    answer = openai.ChatCompletion.create(
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/openai/api_requestor.py", line 674, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
)```

The bot quits.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
one of the following or their combination:
* an error message that a "backend is dead - try again"
* re-try mechanism

+ not quiting prompt

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by adamyodinsky** [comment]
@slonokot Thank you for opening this issue.

This was fixed in the latest version of Terminalgpt v1.0.15, you can upgrade with `pip install terminalgpt -U --user`.

Cheers!
